# Generated by Django 2.2.5 on 2019-10-05 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0005_auto_20191005_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('userprofileinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appOne.UserProfileInfo')),
                ('modules_taken', models.ManyToManyField(to='appOne.Module')),
            ],
            bases=('appOne.userprofileinfo',),
        ),
    ]
