# Generated by Django 2.2.5 on 2019-10-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0008_auto_20191005_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(default='Question', max_length=500)),
                ('question_optionA', models.CharField(max_length=100)),
                ('question_optionB', models.CharField(max_length=100)),
                ('question_optionC', models.CharField(max_length=100)),
                ('question_optionD', models.CharField(max_length=100)),
            ],
            options={
                'permissions': (('can_modify_question', 'Can create/delete a question'),),
            },
        ),
    ]
