# Generated by Django 2.2.5 on 2019-10-07 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0009_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_name',
            field=models.CharField(default='Chapter', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_optionA',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_optionB',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_optionC',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_optionD',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_name', models.CharField(max_length=50)),
                ('solution_answer', models.CharField(max_length=50)),
                ('solution_explanation', models.CharField(max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOne.Question')),
            ],
            options={
                'permissions': (('can_modify_solution', 'Can create/delete a solution'),),
            },
        ),
    ]
