# Generated by Django 2.2.5 on 2019-10-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0010_auto_20191007_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_optionA',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_optionB',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_optionC',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_optionD',
            field=models.CharField(max_length=100),
        ),
    ]
