# Generated by Django 2.2.5 on 2019-10-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0011_auto_20191007_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_name',
            field=models.CharField(max_length=50),
        ),
    ]
