# Generated by Django 2.2.5 on 2019-10-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0012_auto_20191007_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_desc',
            field=models.CharField(max_length=100),
        ),
    ]
