# Generated by Django 2.2.5 on 2019-10-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0013_auto_20191007_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appOne.Chapter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
