# Generated by Django 2.2.5 on 2019-10-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0014_auto_20191007_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='question',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_desc',
            field=models.CharField(default='Description', max_length=100),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
