# Generated by Django 2.2.5 on 2019-10-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0015_auto_20191012_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'permissions': (('can_publish_chapter', 'Can publish a chapter'),)},
        ),
    ]
