# Generated by Django 2.2.5 on 2019-10-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0015_remove_professor_prof_title'),
        ('appOne', '0016_auto_20191012_1224'),
    ]

    operations = [
    ]
