# Generated by Django 2.2.5 on 2019-10-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0017_merge_20191012_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterteam',
            name='room_id',
            field=models.CharField(default='-LqWympLzXhC0wJ0uzqn', max_length=30),
        ),
    ]
