# Generated by Django 2.2.5 on 2019-10-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0018_chapterteam_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterteam',
            name='room_id',
            field=models.CharField(max_length=30),
        ),
    ]
