# Generated by Django 2.2.5 on 2019-10-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0019_auto_20191014_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
