# Generated by Django 2.2.5 on 2019-10-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0020_question_question_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'permissions': (('can_publish_chapter', 'Can publish a chapter'), ('can_try_qn', 'Can try questions in a chapter'))},
        ),
    ]
