# Generated by Django 2.2.5 on 2019-10-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0021_auto_20191015_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterteam',
            name='qn_results',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='chapterteam',
            name='qn_tried',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_teams',
            field=models.ManyToManyField(blank=True, to='appOne.ChapterTeam'),
        ),
    ]
