# Generated by Django 2.2.5 on 2019-11-03 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0022_auto_20191015_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appOne.Question'),
        ),
    ]
